package com.dianping.model;

import java.util.Date;

public class SellerModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.id
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.name
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.created_at
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.updated_at
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.disable_flag
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    private Integer disableFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.remark_score
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    private Integer remarkScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.id
     *
     * @return the value of seller.id
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.id
     *
     * @param id the value for seller.id
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.name
     *
     * @return the value of seller.name
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.name
     *
     * @param name the value for seller.name
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.created_at
     *
     * @return the value of seller.created_at
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.created_at
     *
     * @param createdAt the value for seller.created_at
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.updated_at
     *
     * @return the value of seller.updated_at
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.updated_at
     *
     * @param updatedAt the value for seller.updated_at
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.disable_flag
     *
     * @return the value of seller.disable_flag
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public Integer getDisableFlag() {
        return disableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.disable_flag
     *
     * @param disableFlag the value for seller.disable_flag
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public void setDisableFlag(Integer disableFlag) {
        this.disableFlag = disableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.remark_score
     *
     * @return the value of seller.remark_score
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public Integer getRemarkScore() {
        return remarkScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.remark_score
     *
     * @param remarkScore the value for seller.remark_score
     *
     * @mbg.generated Sun Dec 05 16:12:51 CST 2021
     */
    public void setRemarkScore(Integer remarkScore) {
        this.remarkScore = remarkScore;
    }
}