server:
  port: 8010

mybatis:
  mapper-locations: classpath:mapping/*.xml

# 配置相关数据源

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dianpingDB?&characterEncoding=UTF-8
    username: root
    password: dyh18215153215
    name: dianpingDB
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
# 使用druid做连接池管理